version: '3.7'

services:
  gestionesagre-auth:
    container_name: autenticazione
    restart: always
    build:
      context: .
      dockerfile: src/GestioneSagre.Autenticazione/Dockerfile
    networks:
      - lan-network

networks:
  lan-network:
    external:
      name: docker-net